config { 
  type: "table"
  , schema: "sources" 
  , tags: ["full funnel"]
}

select 
date
,cast(datetime_trunc(cast(date as datetime), week) as date) as week
,cast(datetime_trunc(cast(date as date), month) as date) as month
,'X' as platform 
,lower(Campaign__X_Ads) as campaign
-- ,Campaign_ID__X_Ads as campaign_id
,'' as ad_group
-- ,0 as ad_group_id
,sum(cost) as spend
,sum(clicks) as clicks
,sum(impressions) as impressions


FROM ${ref('funnel_export', 'X_Ads')} 
group by 1,2,3,4,5,6,7